CREATE TYPE "public"."user_platform_roles_role" AS ENUM('super_admin', 'admin', 'desk_lead', 'analyst', 'partner', 'subject_matter_expert', 'finance');--> statement-breakpoint
CREATE TABLE "user_platform_roles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_platform_roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"role" "user_platform_roles_role" NOT NULL,
	"grantedByUserId" integer,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_platform_roles_user_role_unique" UNIQUE("userId","role")
);
--> statement-breakpoint
ALTER TABLE "user_sessions" ADD COLUMN "activeBusinessId" integer;--> statement-breakpoint
ALTER TABLE "user_platform_roles" ADD CONSTRAINT "user_platform_roles_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_platform_roles" ADD CONSTRAINT "user_platform_roles_grantedByUserId_users_id_fk" FOREIGN KEY ("grantedByUserId") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "user_platform_roles_role_idx" ON "user_platform_roles" USING btree ("role");--> statement-breakpoint
ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_activeBusinessId_businesses_id_fk" FOREIGN KEY ("activeBusinessId") REFERENCES "public"."businesses"("id") ON DELETE set null ON UPDATE no action;