CREATE TYPE "public"."payment_requests_delivery_status" AS ENUM('Sent', 'Failed', 'Simulated');--> statement-breakpoint
CREATE TYPE "public"."payment_requests_item" AS ENUM('full_report', 'current_state');--> statement-breakpoint
CREATE TYPE "public"."payment_requests_status" AS ENUM('requested', 'proof_received', 'confirmed');--> statement-breakpoint
CREATE TABLE "payment_requests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payment_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"businessCheckId" integer NOT NULL,
	"item" "payment_requests_item" NOT NULL,
	"amountNaira" integer NOT NULL,
	"reference" varchar(32) NOT NULL,
	"status" "payment_requests_status" DEFAULT 'requested' NOT NULL,
	"requestedByUserId" integer,
	"requestedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"deliveryStatus" "payment_requests_delivery_status" DEFAULT 'Simulated' NOT NULL,
	"proofReceivedAt" timestamp with time zone,
	"confirmedAt" timestamp with time zone,
	"confirmedByUserId" integer,
	"note" varchar(500),
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "payment_requests_reference_unique" UNIQUE("reference")
);
--> statement-breakpoint
ALTER TABLE "payment_requests" ADD CONSTRAINT "payment_requests_businessCheckId_business_checks_id_fk" FOREIGN KEY ("businessCheckId") REFERENCES "public"."business_checks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment_requests" ADD CONSTRAINT "payment_requests_requestedByUserId_users_id_fk" FOREIGN KEY ("requestedByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment_requests" ADD CONSTRAINT "payment_requests_confirmedByUserId_users_id_fk" FOREIGN KEY ("confirmedByUserId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "payment_requests_one_per_check_item" ON "payment_requests" USING btree ("businessCheckId","item");