CREATE TYPE "public"."full_reports_delivery_status" AS ENUM('Sent', 'Failed', 'Simulated');--> statement-breakpoint
CREATE TYPE "public"."full_reports_status" AS ENUM('awaiting_intake', 'delivered');--> statement-breakpoint
CREATE TABLE "full_reports" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "full_reports_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"businessCheckId" integer NOT NULL,
	"paymentRequestId" integer NOT NULL,
	"tokenHash" varchar(64) NOT NULL,
	"status" "full_reports_status" DEFAULT 'awaiting_intake' NOT NULL,
	"intakeJson" text,
	"intakeSubmittedAt" timestamp with time zone,
	"reportVersion" integer,
	"deliveredAt" timestamp with time zone,
	"deliveryStatus" "full_reports_delivery_status" DEFAULT 'Simulated' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "full_reports_businessCheckId_unique" UNIQUE("businessCheckId"),
	CONSTRAINT "full_reports_tokenHash_unique" UNIQUE("tokenHash")
);
--> statement-breakpoint
ALTER TABLE "full_reports" ADD CONSTRAINT "full_reports_businessCheckId_business_checks_id_fk" FOREIGN KEY ("businessCheckId") REFERENCES "public"."business_checks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "full_reports" ADD CONSTRAINT "full_reports_paymentRequestId_payment_requests_id_fk" FOREIGN KEY ("paymentRequestId") REFERENCES "public"."payment_requests"("id") ON DELETE no action ON UPDATE no action;